### ISSUE TITLE
Remove references to `tf.Graph` from API docs.

### ISSUE THREAD

**Issue by frreiss** [CODAIT/graph_def_editor#21]
There are still some references here and there in docstrings to `tf.Graph`, `tf.Tensor`, etc. from the days when this code base was `contrib.graph_editor` and directly modified TensorFlow's Python graph objects. Find the offending docstrings and fix them. Double-check that these references to TensorFlow internal classes are not attached to chunks of code that haven't been properly ported to operate over `GraphDef` protobufs instead of `tf.Graph` objects.

**Comment by BryanCutler** [comment]
I'll work on this
