### ISSUE TITLE
Make GDE Python 2.7 compatible again

### ISSUE THREAD

**Issue by frreiss** [CODAIT/graph_def_editor#32]
IntelliJ thinks that all the code under graph_def_editor is Python 2.7-compatible, but Python 2.7 does not. We'll need to take the some steps to rectify this issue:
* Replace the Python 3.x type hints syntax with the backwards compatible syntax described in [PEP 484](https://www.python.org/dev/peps/pep-0484/). That is:
  ```python
  def _validate_output_shapes_attr(value):
    # type: (Any) -> List[tf.TensorShape]
  ```
  instead of:
  ```
  def _validate_output_shapes_attr(value: Any) -> List[tf.TensorShape]:
  ```
* Replace the calls to `urllib.request` in the three example scripts with something that works in both Python 2.7 and 3.x.
* Add an option to the "env.sh" script to create a Python 2.7 environment if requested.
* Run all the tests and examples with Python 2.7 to verify that they work.

**Comment by BryanCutler** [comment]
> Replace the calls to urllib.request in the three example scripts with something that works in both Python 2.7 and 3.x.

I could take this one Fred

**Comment by frreiss** [comment]
Thanks, @BryanCutler

**Comment by frreiss** [comment]
Type hints PR is in. Other items in this issue still yet to be done.

**Comment by frreiss** [comment]
I think Python 2 is no longer relevant. Closing this PR.
